export interface Province {
  label: string;
  value: string;
  cities: string[];
}

export const provinces: Province[] = [
  {
    label: "New Brunswick",
    value: "NB",
    cities: [
      "Bathurst",
      "Campbellton",
      "Caraquet",
      "Dalhousie",
      "Dieppe",
      "Edmundston",
      "Fredericton",
      "Grand Bay-Westfield",
      "Grand Falls",
      "Hampton",
      "Miramichi",
      "Moncton",
      "Nackawic",
      "Oromocto",
      "Petitcodiac",
      "Quispamsis",
      "Riverview",
      "Rothesay",
      "Sackville",
      "Saint John",
      "Saint Stephen",
      "Shediac",
      "St. Andrews",
      "Sussex",
      "Tracadie-Sheila",
      "Woodstock",
    ],
  },
  {
    label: "Alberta",
    value: "AB",
    cities: [
      "Airdrie",
      "Calgary",
      "Edmonton",
      "Fort McMurray",
      "Grande Prairie",
      "Lethbridge",
      "Medicine Hat",
      "Red Deer",
      "Sherwood Park",
      "Spruce Grove",
      "St. Albert",
    ],
  },
  {
    label: "British Columbia",
    value: "BC",
    cities: [
      "Abbotsford",
      "Burnaby",
      "Chilliwack",
      "Coquitlam",
      "Delta",
      "Kamloops",
      "Kelowna",
      "Langley",
      "Nanaimo",
      "New Westminster",
      "North Vancouver",
      "Prince George",
      "Richmond",
      "Surrey",
      "Vancouver",
      "Victoria",
    ],
  },
  {
    label: "Manitoba",
    value: "MB",
    cities: [
      "Brandon",
      "Dauphin",
      "Portage la Prairie",
      "Selkirk",
      "Steinbach",
      "Thompson",
      "Winkler",
      "Winnipeg",
    ],
  },
  {
    label: "Newfoundland and Labrador",
    value: "NL",
    cities: [
      "Corner Brook",
      "Gander",
      "Grand Falls-Windsor",
      "Happy Valley-Goose Bay",
      "Labrador City",
      "Mount Pearl",
      "Paradise",
      "St. John's",
    ],
  },
  {
    label: "Northwest Territories",
    value: "NT",
    cities: ["Hay River", "Inuvik", "Yellowknife"],
  },
  {
    label: "Nova Scotia",
    value: "NS",
    cities: [
      "Amherst",
      "Bridgewater",
      "Cape Breton",
      "Dartmouth",
      "Glace Bay",
      "Halifax",
      "Kentville",
      "New Glasgow",
      "Sydney",
      "Truro",
      "Yarmouth",
    ],
  },
  {
    label: "Nunavut",
    value: "NU",
    cities: ["Iqaluit", "Rankin Inlet"],
  },
  {
    label: "Ontario",
    value: "ON",
    cities: [
      "Barrie",
      "Brampton",
      "Burlington",
      "Cambridge",
      "Guelph",
      "Hamilton",
      "Kingston",
      "Kitchener",
      "London",
      "Markham",
      "Mississauga",
      "Niagara Falls",
      "Oakville",
      "Oshawa",
      "Ottawa",
      "Richmond Hill",
      "Scarborough",
      "St. Catharines",
      "Sudbury",
      "Thunder Bay",
      "Toronto",
      "Vaughan",
      "Waterloo",
      "Windsor",
    ],
  },
  {
    label: "Prince Edward Island",
    value: "PE",
    cities: ["Charlottetown", "Cornwall", "Stratford", "Summerside"],
  },
  {
    label: "Quebec",
    value: "QC",
    cities: [
      "Gatineau",
      "Granby",
      "Laval",
      "Lévis",
      "Longueuil",
      "Montréal",
      "Québec City",
      "Saguenay",
      "Sherbrooke",
      "Terrebonne",
      "Trois-Rivières",
    ],
  },
  {
    label: "Saskatchewan",
    value: "SK",
    cities: [
      "Moose Jaw",
      "Prince Albert",
      "Regina",
      "Saskatoon",
      "Swift Current",
      "Yorkton",
    ],
  },
  {
    label: "Yukon",
    value: "YT",
    cities: ["Dawson City", "Whitehorse"],
  },
];
